[KEYCLOAK-15692] Fix the MetricsRestServiceTest.testHealthEndpoint test Add ephemeral *.db files generated by Quarkus run to gitignore
Fix MetricsRestServiceTest.testHealthEndpoint failure:
...
Error: OR] Failures:
Error: OR]   MetricsRestServiceTest.testHealthEndpoint:58
-- Expected: response body matches a string containing "{\"status\":\"UP\",\"checks\":[]}"
--      but: was <org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient4Engine$1@78fdb71b>
...

After inspection the current substring match is too strict, adding some
debug prints, the difference is as follows:

Got the following response = {"status":"UP","checks":[{"name":"boot-errors","status":"UP"},{"name":"deployments-status","status":"UP","data":{"keycloak-server.war":"OK"}},{"name":"server-state","status":"UP","data":{"value":"running"}},{"name":"empty-liveness-checks","status":"UP"},{"name":"empty-readiness-checks","status":"UP"}]}
But was expecting {"status":"UP","checks":[]}

The health point test was created before any readiness / liveness checks
were added. Thus make the string match more checks tolerant (since what
actually matters for the test result is the 'UP' status field of the endpoint).

Also add temporary *.db files generated within the quarkus/data directory
upon Quarkus run to gitignore.

Signed-off-by: Jan Lieskovsky <jlieskov@redhat.com>